### ISSUE TITLE
a bug of svn version,please upgrade to the newest svn version,thank you 

### ISSUE THREAD

**Issue by gordonyicang** [elleFlorio/svn-docker#22]
hi

i meet a problem in latest image.

the svn version of latest image is 1.9.7, 

Transmitting file data .svnsync: E160000: SHA1 of reps '97086 3 52814 4194940 02
cd8fba5619943735e5d3b70983e13d c067b31e7165338f23fc62b51b4d5f84446b9f25 97086-22
wy/_6' and '-1 0 52814 4194940 02cd8fba5619943735e5d3b70983e13d c067b31e7165338f
23fc62b51b4d5f84446b9f25 97086-22wy/_6' matches (c067b31e7165338f23fc62b51b4d5f8
4446b9f25) but contents differ

 it is a bug of svn version.
[https://issues.apache.org/jira/projects/SVN/issues/SVN-4722?filter=allissues](url)

how could i upgrade svn version?

or use the v1.9.9 svn version to package a new image?

thank you!

**Comment by elleFlorio** [comment]
Hi, I'll create an image with the new version. Thank you for reporting this!

**Comment by elleFlorio** [comment]
Hi @gordonyicang, unfortunately it is not possible to upgrade SVN. 
The installed version is the latest available for the Alpine Linux version used for the docker image. I cannot upgrade the alpine version because the new versions are affected by a bug that causes a segmentation fault of the apache server, see https://github.com/elleFlorio/svn-docker/issues/12 for details.
I tried to run with the latest Alpine version, but the bug still persists. I think we just have to wait until a new version of Alpine Linux with the bug fixed. 🙁
